// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB25jk8RRWxkwji9brgty0gGJNwRVSuKHI',
    appId: '1:105408176473:web:33f6d2f9a198e33feeec48',
    messagingSenderId: '105408176473',
    projectId: 'minimarketdeudas',
    authDomain: 'minimarketdeudas.firebaseapp.com',
    storageBucket: 'minimarketdeudas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8rqq1zm5Qu56PoHquTx2q33z1vZJ554Q',
    appId: '1:105408176473:android:32ddd3870b2186ddeeec48',
    messagingSenderId: '105408176473',
    projectId: 'minimarketdeudas',
    storageBucket: 'minimarketdeudas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAalM0SWgyheg3a5DVr5kwiPU67UJzvTW4',
    appId: '1:105408176473:ios:ef9058586942fde8eeec48',
    messagingSenderId: '105408176473',
    projectId: 'minimarketdeudas',
    storageBucket: 'minimarketdeudas.appspot.com',
    iosClientId: '105408176473-39dlcitm8c385b45hg3bm44tlialnsk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.deudasMinimarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAalM0SWgyheg3a5DVr5kwiPU67UJzvTW4',
    appId: '1:105408176473:ios:ef9058586942fde8eeec48',
    messagingSenderId: '105408176473',
    projectId: 'minimarketdeudas',
    storageBucket: 'minimarketdeudas.appspot.com',
    iosClientId: '105408176473-39dlcitm8c385b45hg3bm44tlialnsk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.deudasMinimarket',
  );
}
